### ISSUE TITLE
controlling output 

### ISSUE THREAD

**Issue by JVK1987** [chimera0/accel-brain-code#15]
Hi Team,

one i get the output from pysummarization algorithm. can i exclude few sentences based on the keyword.

thanks in advance.

**Comment by chimera0** [comment]
If you know how to use Python `list` s, you should be able to implement it yourself, but why not? Since you don't give a detailed explanation at all, I guess from the fragmentary information, you're not looking at any programming fundamentals apart from the problem with this library.

This place is not a programming school.
