### ISSUE TITLE
MXNetError: GPU is not enabled

### ISSUE THREAD

**Issue by SarahPeterson2854** [chimera0/accel-brain-code#27]
MXNetError: Traceback (most recent call last):
  File "C:\Jenkins\workspace\mxnet-tag\mxnet\src\ndarray\ndarray.cc", line 1298
MXNetError: GPU is not enabled

**Comment by accel-brain** [comment]
Read official documents.
This is not a school that teaches how to use external libraries.

**Comment by SarahPeterson2854** [comment]
Official documents refer to packages that are inconsistent. This has obviously not been tested on a mainstream OS like windows using python. Just pointing out to the future people with the same problem that there is no way to resolve the incompatibility and to not waste their time. The GPU enabling libraries such as mxnet-cu102/92 etc depend on a numpy version that is incompatible with pygan EBGANImageGenerator, GANImageGenerator and EBAAEImageGenerator. Ergo the project is defunct.

**Comment by SarahPeterson2854** [comment]
Reproduce: 
pip install pygan
from pygan.ebgan_image_generator import EBGANImageGenerator
ebgan_image_generator = EBGANImageGenerator(
    # `list` of path to your directories.
    dir_list=[
        "/path/to/your/image/files/", 
    ],
    # `int` of image width.
    width=128,
    # `int` of image height.
    height=96,
    # `int` of image channel.
    channel=1,
    # `int` of batch size.
    batch_size=40,
    # `float` of learning rate.
    learning_rate=1e-06,
)
ebgan_image_generator.learn(
    # `int` of the number of training iterations.
    iter_n=100000,
    # `int` of the number of learning of the discriminative model.
    k_step=10,
)

Will throw gpu not enabled

installing any gpu version for mxnet will then create an incompatibility on windows 10

**Comment by chimera0** [comment]
I will take that suggestion into consideration.
However, I couldn't reproduce it. And I couldn't find any reason to raise the priority of this issue.
The words "windows 10" and "mainstream" don't specify what you mean.
It's understandable If you want to say "not maintained" rather than "not been tested".

As with other issues #28, it's tiring to read your post, which just wrote the error log but didn't specify the context(environment settings, entered information, etc.). Unfortunately, it will take some time to respond.
