### ISSUE TITLE
recommendation system

### ISSUE THREAD

**Issue by Tortoise17** [chimera0/accel-brain-code#7]
I have seen this library very nice and attracted to me for the reinforcement learning. My question is that is this helpful in making recommendation system in terms of reinforcement learning? while performing any task or any workflow / xml based or any manual based?

Please guide

**Comment by chimera0** [comment]
I don't know the details, but It depends on your design for concepts such as policy, states, actions, rewards, etc.

I think you should redefine the problem so that the problem you want to solve in the recommendation system can be solved by reinforcement learning.

Well, it's not a system issue, so I'll close this case.
